name = "cv-site"
compatibility_date = "2025-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

# Use this format (array-of-tables):
[[kv_namespaces]]
binding = "PROFILE_VECTORS"
id = "KV_SECRET"
preview_id = "KV_SECRET"

[vars]
TURNSTILE_SECRET = "$TURNSTILE_SECRET"
GROQ_API_KEY = "$GROQ_API_KEY"
