name = "cv-site"
compatibility_date = "2025-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

# KV Namespaces are configured via Cloudflare Dashboard
# Go to your Pages project → Settings → Functions → KV namespace bindings
# Add binding: PROFILE_VECTORS → your KV namespace
# This keeps the namespace ID secure and out of the public repo

# Runtime environment variables are managed via Cloudflare Dashboard
# These are accessed in code via platform.env.VARIABLE_NAME
# Do NOT set secrets here - use Dashboard Secrets instead
